  server:
    port: 8081

  spring:
    application:
      name: spring-cache

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true

    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://localhost:3306/spring-cache?useUnicode=true&characterEncoding=utf-8&autoreconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      url: jdbc:mysql://localhost:3306/spring-cache?useSSL=false
      username: root
      password: T0kh@66053

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: TRACE